package claude

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/inference-sh/agentprotocol/transcript"
	"github.com/inference-sh/agentprotocol/transcript/transcripttest"
)

// The compacted sample is an interactive run of claude 2.1.281 in the
// harness-test container: a prompt answered through a mock tool call, a
// second prompt, then /compact, which keeps the last two turns (from the
// first turn's answer on) behind the summary.
const (
	compactedCWD = "/tmp/harness-test-claude-4243253944/test-repo"
	compactedID  = "6deafb15-b5f3-476d-85d6-0d87ecca9ff4"
)

var compacted = transcripttest.Sample{Home: "testdata/home", CWD: compactedCWD, ID: compactedID}

func TestCompactedRoundTrip(t *testing.T) {
	transcripttest.RoundTrip(t, Codec, compacted)
}

func TestCompactedAppend(t *testing.T) {
	transcripttest.Append(t, Codec, compacted)
}

type seen struct {
	role     transcript.Role
	audience transcript.Audience
	text     string
}

func summarize(es []transcript.Entry) []seen {
	out := make([]seen, len(es))
	for i, e := range es {
		text := e.Text()
		if i := strings.IndexByte(text, '\n'); i >= 0 {
			text = text[:i]
		}
		for _, b := range e.Content {
			switch b.Kind {
			case transcript.BlockToolUse:
				text += "[use " + b.ToolID + "]"
			case transcript.BlockToolResult:
				text += "[result " + b.ToolID + "]"
			}
		}
		out[i] = seen{e.Role, e.Audience, text}
	}
	return out
}

func expect(t *testing.T, what string, got []transcript.Entry, want []seen) {
	t.Helper()
	g := summarize(got)
	if len(g) != len(want) {
		t.Errorf("%s: %d entries, want %d", what, len(g), len(want))
	}
	for i := range max(len(g), len(want)) {
		var a, b seen
		if i < len(g) {
			a = g[i]
		}
		if i < len(want) {
			b = want[i]
		}
		if a != b {
			t.Errorf("%s[%d] = %+v, want %+v", what, i, a, b)
		}
	}
}

// TestCompactedResume: the rows /compact kept still name their parents from
// before it, and the boundary has no parent. Claude splices them in behind
// the summary and drops the turn the compaction retired: the model gets the
// summary, the kept turns and the /compact exchange. The retired turn is
// linked in ahead of the boundary, through its logicalParentUuid, so the
// person's view and a move to another agent keep it.
func TestCompactedResume(t *testing.T) {
	st, err := Codec.Open(compacted.Home)
	if err != nil {
		t.Fatal(err)
	}
	s, err := st.Read(t.Context(), compactedID)
	if err != nil {
		t.Fatal(err)
	}
	const (
		summary = "This session is being continued from a previous conversation that ran out of context. The summary below covers the earlier portion of the conversation."
		caveat  = "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"
		command = "<command-name>/compact</command-name>"
		stdout  = "<local-command-stdout>Compacted (ctrl+o to see full summary)"
		hello   = "Hello from mock server."
		more    = "Tell me more about the project."
		first   = "What is the project codename? Reply ONLY the codename."
	)
	all, model := transcript.AudienceAll, transcript.AudienceModel
	expect(t, "context", s.Context(), []seen{
		{transcript.RoleUser, all, summary},
		{transcript.RoleAssistant, all, hello},
		{transcript.RoleUser, all, more},
		{transcript.RoleAssistant, all, hello},
		{transcript.RoleUser, model, caveat},
		{transcript.RoleUser, all, command},
		{transcript.RoleUser, all, stdout},
	})
	expect(t, "linearize", s.Linearize(), []seen{
		{transcript.RoleUser, all, first},
		{transcript.RoleAssistant, all, "[use toolu_mock_1]"},
		{transcript.RoleTool, all, "[result toolu_mock_1]"},
		{transcript.RoleAssistant, all, hello},
		{transcript.RoleUser, all, more},
		{transcript.RoleAssistant, all, hello},
		{transcript.RoleUser, all, command},
		{transcript.RoleUser, all, stdout},
	})
	// Moved to another agent, the session keeps the summary, the one
	// record of what the compaction retired, and leaves the caveat.
	expect(t, "portable", s.Portable().Lower(transcript.Capabilities{}).Entries, []seen{
		{transcript.RoleUser, all, summary},
		{transcript.RoleAssistant, all, hello},
		{transcript.RoleUser, all, more},
		{transcript.RoleAssistant, all, hello},
		{transcript.RoleUser, all, command},
		{transcript.RoleUser, all, stdout},
	})
	// The chain ends on the attachments the /compact turn left, where the
	// next prompt links.
	if s.Leaf != "e9b82443-fc13-471d-a0ce-695afb159d59" {
		t.Errorf("leaf = %s", s.Leaf)
	}
}

// fixture writes rows as a Claude session file under a fresh home and reads
// it back.
type fixture struct {
	t    *testing.T
	rows []string
	at   time.Time
}

const (
	fixtureCWD = "/tmp/fixture/project"
	fixtureID  = "7d1f7a52-6a44-4d4e-9d7c-0b8a51d5f0a1"
)

func newFixture(t *testing.T) *fixture {
	return &fixture{t: t, at: time.Date(2026, 9, 1, 10, 0, 0, 0, time.UTC)}
}

// uid names fixture row n.
func uid(n int) string { return fmt.Sprintf("00000000-0000-4000-8000-%012d", n) }

// row appends a message row with the fields every Claude row carries.
func (f *fixture) row(typ string, n, parent int, fields map[string]any) {
	f.at = f.at.Add(100 * time.Millisecond)
	r := map[string]any{
		"parentUuid":  nil,
		"isSidechain": false,
		"type":        typ,
		"uuid":        uid(n),
		"timestamp":   f.at.Format("2006-01-02T15:04:05.000Z"),
		"userType":    "external",
		"entrypoint":  "cli",
		"cwd":         fixtureCWD,
		"sessionId":   fixtureID,
		"version":     "2.1.281",
		"gitBranch":   "main",
	}
	if parent > 0 {
		r["parentUuid"] = uid(parent)
	}
	for k, v := range fields {
		r[k] = v
	}
	f.raw(r)
}

func (f *fixture) raw(r map[string]any) {
	b, err := json.Marshal(r)
	if err != nil {
		f.t.Fatal(err)
	}
	f.rows = append(f.rows, string(b))
}

func (f *fixture) prompt(n, parent int, text string) {
	f.row("user", n, parent, map[string]any{"promptId": uid(9000 + n), "message": map[string]any{"role": "user", "content": text}})
}

// reply appends one row of assistant message id, holding the blocks
// Claude's streaming emits for one content_block_stop.
func (f *fixture) reply(n, parent int, id string, blocks ...map[string]any) {
	f.row("assistant", n, parent, map[string]any{
		"requestId": "req_" + id,
		"message": map[string]any{
			"model": "claude-opus-4-6", "id": id, "type": "message", "role": "assistant",
			"content": blocks, "stop_reason": "tool_use", "stop_sequence": nil,
			"usage": map[string]any{"input_tokens": 3, "output_tokens": 12},
		},
	})
}

// result appends a tool result whose parent is the row that made the call,
// as insertMessageChain links it through sourceToolAssistantUUID
// (sessionStorage.ts:1033).
func (f *fixture) result(n, call int, toolID string) {
	f.row("user", n, call, map[string]any{
		"promptId":                uid(9000 + n),
		"message":                 map[string]any{"role": "user", "content": []map[string]any{{"tool_use_id": toolID, "type": "tool_result", "content": "ok " + toolID, "is_error": false}}},
		"toolUseResult":           map[string]any{"stdout": "ok " + toolID},
		"sourceToolAssistantUUID": uid(call),
	})
}

func text(s string) map[string]any { return map[string]any{"type": "text", "text": s} }

func use(id string) map[string]any {
	return map[string]any{"type": "tool_use", "id": id, "name": "Read", "input": map[string]any{"file_path": "/tmp/" + id}}
}

func (f *fixture) lastPrompt(prompt string, leaf int, extra map[string]any) {
	r := map[string]any{"type": "last-prompt", "lastPrompt": prompt, "leafUuid": uid(leaf), "sessionId": fixtureID}
	for k, v := range extra {
		r[k] = v
	}
	f.raw(r)
}

func (f *fixture) read() *transcript.Session {
	f.t.Helper()
	home := f.t.TempDir()
	dir := filepath.Join(home, ".claude", "projects", transcript.MangledCwd.Name(fixtureCWD))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		f.t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, fixtureID+".jsonl"), []byte(strings.Join(f.rows, "\n")+"\n"), 0o644); err != nil {
		f.t.Fatal(err)
	}
	st, err := Codec.Open(home)
	if err != nil {
		f.t.Fatal(err)
	}
	s, err := st.Read(f.t.Context(), fixtureID)
	if err != nil {
		f.t.Fatal(err)
	}
	return s
}

// TestParallelToolCalls: one assistant message with two tool calls is
// written as a row per content block sharing message.id, each chained to
// the one before, and each result hangs off the row of its own call
// (claude.ts emits a message per content_block_stop; the result's parent
// is its sourceToolAssistantUUID). The walk up from the leaf passes through
// the second result only. The mock server behind the harness-test container
// answers with one tool call at a time, so this shape is written by hand
// after real 2.1.x files.
func TestParallelToolCalls(t *testing.T) {
	f := newFixture(t)
	f.prompt(1, 0, "Read a and b.")
	f.reply(2, 1, "msg_A", text("Reading both."))
	f.reply(3, 2, "msg_A", use("toolu_a"))
	f.reply(4, 3, "msg_A", use("toolu_b"))
	f.result(5, 3, "toolu_a")
	f.result(6, 4, "toolu_b")
	f.reply(7, 6, "msg_B", text("Both read."))
	f.lastPrompt("Read a and b.", 7, nil)
	s := f.read()

	all := transcript.AudienceAll
	want := []seen{
		{transcript.RoleUser, all, "Read a and b."},
		{transcript.RoleAssistant, all, "Reading both.[use toolu_a][use toolu_b]"},
		{transcript.RoleTool, all, "[result toolu_a]"},
		{transcript.RoleTool, all, "[result toolu_b]"},
		{transcript.RoleAssistant, all, "Both read."},
	}
	expect(t, "context", s.Context(), want)
	expect(t, "linearize", s.Linearize(), want)
	if s.Leaf != uid(7) {
		t.Errorf("leaf = %s, want %s", s.Leaf, uid(7))
	}
}

// TestStreamedToolCalls: when a tool runs while the message is still
// streaming, its result is written before the message's next row, which
// links to it. The chain holds every row; the API call still gets one
// assistant message followed by the results (normalizeMessagesForAPI).
func TestStreamedToolCalls(t *testing.T) {
	f := newFixture(t)
	f.prompt(1, 0, "Read a and b.")
	f.reply(2, 1, "msg_A", use("toolu_a"))
	f.result(3, 2, "toolu_a")
	f.reply(4, 3, "msg_A", use("toolu_b"))
	f.result(5, 4, "toolu_b")
	f.reply(6, 5, "msg_B", text("Both read."))
	s := f.read()

	all := transcript.AudienceAll
	expect(t, "context", s.Context(), []seen{
		{transcript.RoleUser, all, "Read a and b."},
		{transcript.RoleAssistant, all, "[use toolu_a][use toolu_b]"},
		{transcript.RoleTool, all, "[result toolu_a]"},
		{transcript.RoleTool, all, "[result toolu_b]"},
		{transcript.RoleAssistant, all, "Both read."},
	})
}

// TestRewindPin: a rewind leaves the undone turn in the file and writes a
// last-prompt row with explicit:true naming the message to resume from.
// Claude Code 2.1.281 writes it from its rewind path ({type:"last-prompt",
// leafUuid, explicit:true, rewound:true}); the source snapshot predates it,
// so this shape is written by hand. The pin holds until a message row is
// written after it.
func TestRewindPin(t *testing.T) {
	f := newFixture(t)
	f.prompt(1, 0, "first")
	f.reply(2, 1, "msg_A", text("one"))
	f.lastPrompt("first", 2, nil)
	f.prompt(3, 2, "second")
	f.reply(4, 3, "msg_B", text("two"))
	f.lastPrompt("first", 2, map[string]any{"explicit": true, "rewound": true})
	s := f.read()

	all := transcript.AudienceAll
	want := []seen{
		{transcript.RoleUser, all, "first"},
		{transcript.RoleAssistant, all, "one"},
	}
	if s.Leaf != uid(2) {
		t.Errorf("leaf = %s, want %s", s.Leaf, uid(2))
	}
	expect(t, "context", s.Context(), want)

	// The next prompt continues from the pin, and the pin no longer holds.
	f.prompt(5, 2, "third")
	f.reply(6, 5, "msg_C", text("three"))
	s = f.read()
	expect(t, "after the rewind", s.Context(), []seen{
		{transcript.RoleUser, all, "first"},
		{transcript.RoleAssistant, all, "one"},
		{transcript.RoleUser, all, "third"},
		{transcript.RoleAssistant, all, "three"},
	})

	// A last-prompt row the turn loop writes (no explicit) names the turn's
	// prompt; the rows after it that descend from it win.
	f = newFixture(t)
	f.lastPrompt("first", 1, nil)
	f.prompt(1, 0, "first")
	f.reply(2, 1, "msg_A", text("one"))
	if s := f.read(); s.Leaf != uid(2) {
		t.Errorf("turn loop pin: leaf = %s, want %s", s.Leaf, uid(2))
	}
}

// TestSidechainNotLeaf: rows of a subagent's conversation (isSidechain,
// written into the session file by older versions) never become the leaf,
// however late they are written.
func TestSidechainNotLeaf(t *testing.T) {
	f := newFixture(t)
	f.prompt(1, 0, "delegate")
	f.reply(2, 1, "msg_A", text("done"))
	f.row("user", 3, 0, map[string]any{"isSidechain": true, "agentId": "a1", "message": map[string]any{"role": "user", "content": "subtask"}})
	f.row("assistant", 4, 3, map[string]any{"isSidechain": true, "agentId": "a1", "message": map[string]any{"role": "assistant", "id": "msg_S", "content": []map[string]any{text("sub done")}}})
	s := f.read()

	all := transcript.AudienceAll
	expect(t, "context", s.Context(), []seen{
		{transcript.RoleUser, all, "delegate"},
		{transcript.RoleAssistant, all, "done"},
	})
}

// TestAudience: an isMeta user row is sent and not shown, and an API error
// Claude shows in place of a reply (isApiErrorMessage, model <synthetic>)
// is shown and not sent.
func TestAudience(t *testing.T) {
	f := newFixture(t)
	f.prompt(1, 0, "go")
	f.row("user", 2, 1, map[string]any{"isMeta": true, "message": map[string]any{"role": "user", "content": "skill body"}})
	f.row("assistant", 3, 2, map[string]any{"isApiErrorMessage": true, "message": map[string]any{
		"role": "assistant", "id": "msg_E", "model": "<synthetic>", "content": []map[string]any{text("API Error: overloaded")},
	}})
	s := f.read()

	all := transcript.AudienceAll
	expect(t, "context", s.Context(), []seen{
		{transcript.RoleUser, all, "go"},
		{transcript.RoleUser, transcript.AudienceModel, "skill body"},
	})
	expect(t, "linearize", s.Linearize(), []seen{
		{transcript.RoleUser, all, "go"},
		{transcript.RoleAssistant, transcript.AudienceUser, "API Error: overloaded"},
	})
}

// TestAppendStamps: turns appended without a time are written after every
// row the file holds, each later than the one before.
func TestAppendStamps(t *testing.T) {
	st, err := Codec.Open(compacted.Home)
	if err != nil {
		t.Fatal(err)
	}
	s, err := st.Read(t.Context(), compactedID)
	if err != nil {
		t.Fatal(err)
	}
	// The file's own time can be older than its rows (a copy that kept an
	// old mtime); new rows must still come after them.
	s.Updated = time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)
	s.Entries = append(s.Entries,
		transcript.Entry{Role: transcript.RoleUser, Content: []transcript.Block{{Kind: transcript.BlockText, Text: "again"}}},
		transcript.Entry{Role: transcript.RoleAssistant, Content: []transcript.Block{{Kind: transcript.BlockText, Text: "sure"}}},
	)
	home := t.TempDir()
	dst, err := Codec.Open(home)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := dst.Write(t.Context(), s); err != nil {
		t.Fatal(err)
	}
	fh, err := os.Open(filepath.Join(home, ".claude", "projects", transcript.MangledCwd.Name(compactedCWD), compactedID+".jsonl"))
	if err != nil {
		t.Fatal(err)
	}
	defer fh.Close()
	var stamps []string
	sc := bufio.NewScanner(fh)
	sc.Buffer(nil, 1<<20)
	for sc.Scan() {
		var r struct {
			Timestamp string `json:"timestamp"`
		}
		if json.Unmarshal(sc.Bytes(), &r) == nil && r.Timestamp != "" {
			stamps = append(stamps, r.Timestamp)
		}
	}
	n := len(stamps)
	latest := ""
	for _, ts := range stamps[:n-2] {
		latest = max(latest, ts)
	}
	if !(latest < stamps[n-2] && stamps[n-2] < stamps[n-1]) {
		t.Errorf("appended rows stamped %s, %s after rows up to %s", stamps[n-2], stamps[n-1], latest)
	}
}

// TestRewindToStart: a rewind past the first prompt writes a last-prompt row
// with leafUuid null and explicit:true (Claude Code 2.1.281's rewind path,
// binary only), and Claude resumes with nothing.
func TestRewindToStart(t *testing.T) {
	f := newFixture(t)
	f.prompt(1, 0, "first")
	f.reply(2, 1, "msg_A", text("one"))
	f.raw(map[string]any{"type": "last-prompt", "leafUuid": nil, "explicit": true, "sessionId": fixtureID})
	s := f.read()
	if ctx, lin := s.Context(), s.Linearize(); len(ctx) != 0 || len(lin) != 0 {
		t.Errorf("context %d, linearize %d entries, want none", len(ctx), len(lin))
	}
	// The next prompt starts over, as Claude's would, rather than bringing
	// the rewound history back.
	s.Entries = append(s.Entries, transcript.Entry{Role: transcript.RoleUser, Content: []transcript.Block{{Kind: transcript.BlockText, Text: "again"}}})
	st, err := Codec.Open(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	if _, err := st.Write(t.Context(), s); err != nil {
		t.Fatal(err)
	}
	back, err := st.Read(t.Context(), fixtureID)
	if err != nil {
		t.Fatal(err)
	}
	if lin := back.Linearize(); len(lin) != 1 || lin[0].Text() != "again" {
		t.Errorf("after the rewind, an appended prompt reads back as %d entries", len(lin))
	}
}

// TestRetiredWithoutLogicalParent: the main sample's boundary names as its
// logical parent a row Claude never wrote to the file, so the retired
// history is found from the end of the segment the compaction kept.
func TestRetiredWithoutLogicalParent(t *testing.T) {
	st, err := Codec.Open("testdata/home")
	if err != nil {
		t.Fatal(err)
	}
	s, err := st.Read(t.Context(), sampleID)
	if err != nil {
		t.Fatal(err)
	}
	all := transcript.AudienceAll
	hello := "Hello from mock server."
	expect(t, "linearize", s.Linearize()[:4], []seen{
		{transcript.RoleUser, all, "What is the project codename? Reply ONLY the codename."},
		{transcript.RoleAssistant, all, "[use toolu_mock_1]"},
		{transcript.RoleTool, all, "[result toolu_mock_1]"},
		{transcript.RoleAssistant, all, hello},
	})
	expect(t, "context", s.Context()[:2], []seen{
		{transcript.RoleUser, all, "This session is being continued from a previous conversation that ran out of context. The summary below covers the earlier portion of the conversation."},
		{transcript.RoleAssistant, all, hello},
	})
}
