// Command schemagen derives Go types for the Codex app-server protocol from
// the JSON Schema the codex binary publishes about itself.
//
// It runs `codex app-server generate-json-schema` (stable surface only, no
// --experimental), reads the bundled schema, and writes Go declarations for a
// fixed set of root types plus everything they reference. It also writes a
// constant for every method named in the ClientRequest, ServerRequest,
// ServerNotification and ClientNotification unions.
//
// Regenerate from the codexapp directory with:
//
//	go generate ./...
//
// or point it at a schema directory produced earlier with -schema.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

// roots are the protocol types this client uses. Everything they reference is
// generated too.
var roots = []string{
	// Handshake and thread lifecycle.
	"InitializeParams", "InitializeResponse",
	"ThreadStartParams", "ThreadStartResponse",
	"ThreadResumeParams", "ThreadResumeResponse",
	"TurnStartParams", "TurnStartResponse",
	"TurnSteerParams", "TurnSteerResponse",
	"TurnInterruptParams", "TurnInterruptResponse",

	// Requests the server makes of the client.
	"CommandExecutionRequestApprovalParams", "CommandExecutionRequestApprovalResponse",
	"FileChangeRequestApprovalParams", "FileChangeRequestApprovalResponse",
	"PermissionsRequestApprovalParams", "PermissionsRequestApprovalResponse",
	"ExecCommandApprovalParams", "ExecCommandApprovalResponse",
	"ApplyPatchApprovalParams", "ApplyPatchApprovalResponse",

	// Notifications the driver maps.
	"ErrorNotification",
	"ThreadStartedNotification", "ThreadStatusChangedNotification",
	"TurnStartedNotification", "TurnCompletedNotification",
	"ItemStartedNotification", "ItemCompletedNotification",
	"AgentMessageDeltaNotification",
	"ReasoningTextDeltaNotification", "ReasoningSummaryTextDeltaNotification",
	"CommandExecutionOutputDeltaNotification",
	"ThreadTokenUsageUpdatedNotification",
	"ServerRequestResolvedNotification",
	"ContextCompactedNotification",
	"WarningNotification", "ConfigWarningNotification",
}

func main() {
	codex := flag.String("codex", "codex", "codex binary to ask for its schema")
	schemaDir := flag.String("schema", "", "use this generate-json-schema output directory instead of running codex")
	out := flag.String("out", "protocol_gen.go", "output file")
	pkg := flag.String("pkg", "codexapp", "package name")
	flag.Parse()

	version := "unknown"
	dir := *schemaDir
	if dir == "" {
		v, err := exec.Command(*codex, "--version").Output()
		if err != nil {
			fail("codex --version: %v", err)
		}
		version = strings.TrimSpace(string(v))
		tmp, err := os.MkdirTemp("", "codex-schema-")
		if err != nil {
			fail("temp dir: %v", err)
		}
		defer os.RemoveAll(tmp)
		cmd := exec.Command(*codex, "app-server", "generate-json-schema", "--out", tmp)
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			fail("generate-json-schema: %v", err)
		}
		dir = tmp
	} else if b, err := os.ReadFile(filepath.Join(dir, "VERSION")); err == nil {
		version = strings.TrimSpace(string(b))
	}

	raw, err := os.ReadFile(filepath.Join(dir, "codex_app_server_protocol.schemas.json"))
	if err != nil {
		fail("read schema bundle: %v", err)
	}
	var bundle map[string]any
	if err := json.Unmarshal(raw, &bundle); err != nil {
		fail("parse schema bundle: %v", err)
	}

	g := newGen(bundle)
	for _, r := range roots {
		if g.lookup(r) == nil {
			fail("root %s is not in the schema", r)
		}
		g.need(r)
	}
	g.run()

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by codexapp/internal/schemagen from %s's app-server JSON Schema. DO NOT EDIT.\n\n", version)
	fmt.Fprintf(&buf, "package %s\n\n", *pkg)
	buf.WriteString("import \"encoding/json\"\n\n")
	fmt.Fprintf(&buf, "// SchemaVersion is the codex version these types were generated from.\nconst SchemaVersion = %q\n\n", version)
	g.writeMethods(&buf)
	names := make([]string, 0, len(g.decls))
	for n := range g.decls {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		buf.WriteString(g.decls[n])
		buf.WriteString("\n")
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		os.WriteFile(*out+".broken", buf.Bytes(), 0o644)
		fail("gofmt: %v (unformatted output in %s.broken)", err, *out)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fail("write: %v", err)
	}
}

func fail(f string, a ...any) {
	fmt.Fprintf(os.Stderr, "schemagen: "+f+"\n", a...)
	os.Exit(1)
}

type node = map[string]any

type gen struct {
	top, v2 map[string]any
	bundle  node
	queue   []string
	queued  map[string]bool
	decls   map[string]string
	// inline holds synthetic declarations for anonymous nested types, keyed
	// by the name given to them.
	inline map[string]node
}

func newGen(b node) *gen {
	defs, _ := b["definitions"].(map[string]any)
	v2, _ := defs["v2"].(map[string]any)
	return &gen{
		top: defs, v2: v2, bundle: b,
		queued: map[string]bool{}, decls: map[string]string{}, inline: map[string]node{},
	}
}

// lookup finds a named definition. The bundle holds the v1 surface at the top
// and the v2 surface under definitions.v2; the two names that appear in both
// are identical apart from a title.
func (g *gen) lookup(name string) node {
	if n, ok := g.inline[name]; ok {
		return n
	}
	if n, ok := g.v2[name].(map[string]any); ok {
		return n
	}
	if name == "v2" {
		return nil
	}
	if n, ok := g.top[name].(map[string]any); ok {
		return n
	}
	return nil
}

func (g *gen) need(name string) {
	if !g.queued[name] {
		g.queued[name] = true
		g.queue = append(g.queue, name)
	}
}

func (g *gen) run() {
	for len(g.queue) > 0 {
		n := g.queue[0]
		g.queue = g.queue[1:]
		g.declare(n, g.lookup(n))
	}
}

func refName(ref string) string {
	return ref[strings.LastIndex(ref, "/")+1:]
}

// --- classification ---

func str(n node, k string) string { s, _ := n[k].(string); return s }

func list(n node, k string) []any { l, _ := n[k].([]any); return l }

func types(n node) []string {
	switch t := n["type"].(type) {
	case string:
		return []string{t}
	case []any:
		var out []string
		for _, x := range t {
			if s, ok := x.(string); ok {
				out = append(out, s)
			}
		}
		return out
	}
	return nil
}

func hasType(n node, t string) bool {
	for _, x := range types(n) {
		if x == t {
			return true
		}
	}
	return false
}

func isNull(v any) bool {
	n, ok := v.(map[string]any)
	return ok && len(types(n)) == 1 && types(n)[0] == "null" && n["$ref"] == nil
}

// nonNull strips a nullable wrapper: anyOf [X, null], allOf [X], or a type
// list that includes "null". It reports whether null was allowed.
func nonNull(n node) (node, bool) {
	nullable := false
	for {
		if alts := list(n, "anyOf"); len(alts) == 2 && (isNull(alts[0]) || isNull(alts[1])) {
			nullable = true
			if isNull(alts[0]) {
				n = alts[1].(map[string]any)
			} else {
				n = alts[0].(map[string]any)
			}
			continue
		}
		if alts := list(n, "allOf"); len(alts) == 1 {
			inner := alts[0].(map[string]any)
			n = inner
			continue
		}
		break
	}
	if ts := types(n); len(ts) == 2 && hasType(n, "null") {
		nullable = true
		c := node{}
		for k, v := range n {
			c[k] = v
		}
		for _, t := range ts {
			if t != "null" {
				c["type"] = t
			}
		}
		n = c
	}
	return n, nullable
}

func variants(n node) []any {
	if v := list(n, "oneOf"); v != nil {
		return v
	}
	return list(n, "anyOf")
}

func isStringEnum(n node) bool {
	if hasType(n, "string") && len(list(n, "enum")) > 0 {
		return true
	}
	vs := variants(n)
	if len(vs) == 0 {
		return false
	}
	for _, v := range vs {
		vn, ok := v.(map[string]any)
		if !ok || !hasType(vn, "string") || len(list(vn, "enum")) == 0 {
			return false
		}
	}
	return true
}

// tag reports the discriminator of a tagged union: every variant an object
// whose "type" property is a single-value enum.
func tagged(n node) bool {
	vs := variants(n)
	if len(vs) == 0 {
		return false
	}
	for _, v := range vs {
		vn, ok := v.(map[string]any)
		if !ok {
			return false
		}
		if tagValue(vn) == "" {
			return false
		}
	}
	return true
}

func tagValue(v node) string {
	props, _ := v["properties"].(map[string]any)
	t, _ := props["type"].(map[string]any)
	if t == nil {
		return ""
	}
	e := list(t, "enum")
	if len(e) != 1 {
		return ""
	}
	s, _ := e[0].(string)
	return s
}

// --- naming ---

var nonAlnum = regexp.MustCompile(`[^A-Za-z0-9]+`)

var initialisms = map[string]string{"Id": "ID", "Ids": "IDs", "Url": "URL", "Uri": "URI", "Json": "JSON", "Http": "HTTP", "Sdp": "SDP", "Mcp": "MCP"}

// pascal turns a wire name into an exported Go identifier.
func pascal(s string) string {
	parts := nonAlnum.Split(s, -1)
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		// Split camelCase into words so initialisms apply per word.
		var words []string
		start := 0
		for i := 1; i < len(p); i++ {
			if unicode.IsUpper(rune(p[i])) && !unicode.IsUpper(rune(p[i-1])) {
				words = append(words, p[start:i])
				start = i
			}
		}
		words = append(words, p[start:])
		for _, w := range words {
			w = strings.ToUpper(w[:1]) + w[1:]
			if r, ok := initialisms[w]; ok {
				w = r
			}
			b.WriteString(w)
		}
	}
	out := b.String()
	if out == "" {
		return "X"
	}
	if unicode.IsDigit(rune(out[0])) {
		out = "V" + out
	}
	return out
}

// typeName keeps definition names as the vendor spelled them, only making them
// valid identifiers.
func typeName(s string) string {
	s = nonAlnum.ReplaceAllString(s, "")
	if s == "" {
		return "X"
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// --- emission ---

func comment(desc, indent string) string {
	desc = strings.TrimSpace(desc)
	if desc == "" {
		return ""
	}
	var b strings.Builder
	for _, l := range strings.Split(desc, "\n") {
		b.WriteString(indent + "// " + strings.TrimRight(l, " ") + "\n")
	}
	return strings.ReplaceAll(b.String(), "// \n", "//\n")
}

func (g *gen) declare(name string, n node) {
	if n == nil {
		fail("no definition for %s", name)
	}
	var b strings.Builder
	b.WriteString(comment(str(n, "description"), ""))
	tn := typeName(name)
	inner, _ := nonNull(n)

	switch {
	case isStringEnum(inner):
		fmt.Fprintf(&b, "type %s string\n\nconst (\n", tn)
		for _, v := range enumValues(inner) {
			b.WriteString(comment(v.desc, "\t"))
			fmt.Fprintf(&b, "\t%s%s %s = %q\n", tn, pascal(v.value), tn, v.value)
		}
		b.WriteString(")\n")

	case tagged(inner):
		g.writeTagged(&b, tn, inner)

	case len(variants(inner)) > 0:
		g.writeRawUnion(&b, tn, inner)

	case hasType(inner, "object") || inner["properties"] != nil:
		if props, _ := inner["properties"].(map[string]any); len(props) > 0 {
			g.writeStruct(&b, tn, inner)
		} else {
			fmt.Fprintf(&b, "type %s = %s\n", tn, g.goType(inner, tn))
		}

	default:
		fmt.Fprintf(&b, "type %s = %s\n", tn, g.goType(inner, tn))
	}
	g.decls[tn] = b.String()
}

type enumValue struct{ value, desc string }

func enumValues(n node) []enumValue {
	var out []enumValue
	if e := list(n, "enum"); len(e) > 0 {
		for _, x := range e {
			if s, ok := x.(string); ok {
				out = append(out, enumValue{value: s})
			}
		}
		return out
	}
	for _, v := range variants(n) {
		vn := v.(map[string]any)
		for _, x := range list(vn, "enum") {
			if s, ok := x.(string); ok {
				out = append(out, enumValue{value: s, desc: str(vn, "description")})
			}
		}
	}
	return out
}

func (g *gen) writeStruct(b *strings.Builder, tn string, n node) {
	props, _ := n["properties"].(map[string]any)
	required := map[string]bool{}
	for _, r := range list(n, "required") {
		required[r.(string)] = true
	}
	keys := make([]string, 0, len(props))
	for k := range props {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	fmt.Fprintf(b, "type %s struct {\n", tn)
	used := map[string]bool{}
	for _, k := range keys {
		pv := props[k]
		pn, ok := pv.(map[string]any)
		if !ok {
			pn = node{}
		}
		field := pascal(k)
		for used[field] {
			field += "_"
		}
		used[field] = true
		inner, nullable := nonNull(pn)
		gt := g.goType(inner, tn+field)
		omit := !required[k] || nullable
		if omit && pointerable(gt) && !g.isRawUnion(gt) {
			gt = "*" + gt
		}
		desc := str(pn, "description")
		if desc == "" {
			desc = str(inner, "description")
		}
		b.WriteString(comment(desc, "\t"))
		tag := k
		if !required[k] {
			tag += ",omitempty"
		}
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", field, gt, tag)
	}
	b.WriteString("}\n")
}

// pointerable reports whether an optional field of this type needs a pointer
// to tell absent from zero. Slices, maps and raw JSON already have a nil.
func pointerable(gt string) bool {
	if strings.HasPrefix(gt, "[]") || strings.HasPrefix(gt, "map[") || gt == "json.RawMessage" || gt == "any" {
		return false
	}
	return true
}

// isRawUnion reports whether a named type is declared as raw JSON, which has
// its own nil and needs no pointer.
func (g *gen) isRawUnion(name string) bool {
	n := g.lookup(name)
	if n == nil {
		return false
	}
	inner, _ := nonNull(n)
	return len(variants(inner)) > 0 && !isStringEnum(inner) && !tagged(inner)
}

// writeTagged declares a union discriminated by its "type" property: one
// struct per variant, and a union type that keeps the raw JSON so unknown
// variants survive a round trip.
func (g *gen) writeTagged(b *strings.Builder, tn string, n node) {
	fmt.Fprintf(b, "type %s struct {\n\tType string\n\tRaw json.RawMessage\n}\n\n", tn)
	fmt.Fprintf(b, "func (u *%s) UnmarshalJSON(data []byte) error {\n", tn)
	b.WriteString("\tvar head struct{ Type string `json:\"type\"` }\n")
	b.WriteString("\tif err := json.Unmarshal(data, &head); err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\tu.Type = head.Type\n\tu.Raw = append(u.Raw[:0], data...)\n\treturn nil\n}\n\n")
	fmt.Fprintf(b, "func (u %s) MarshalJSON() ([]byte, error) {\n\tif len(u.Raw) == 0 {\n\t\treturn []byte(\"null\"), nil\n\t}\n\treturn u.Raw, nil\n}\n\n", tn)
	fmt.Fprintf(b, "const (\n")
	type vinfo struct{ tag, name string }
	var vs []vinfo
	for _, v := range variants(n) {
		vn := v.(map[string]any)
		tag := tagValue(vn)
		name := typeName(str(vn, "title"))
		if str(vn, "title") == "" {
			name = tn + pascal(tag)
		}
		vs = append(vs, vinfo{tag, name})
		fmt.Fprintf(b, "\t%sType%s = %q\n", tn, pascal(tag), tag)
		g.inline[name] = vn
		g.need(name)
	}
	b.WriteString(")\n\n")
	for _, v := range vs {
		fmt.Fprintf(b, "// As%s decodes the variant when Type is %q.\n", v.name, v.tag)
		fmt.Fprintf(b, "func (u %s) As%s() (%s, bool) {\n\tvar v %s\n\tif u.Type != %q || json.Unmarshal(u.Raw, &v) != nil {\n\t\treturn v, false\n\t}\n\treturn v, true\n}\n\n", tn, v.name, v.name, v.name, v.tag)
	}
	fmt.Fprintf(b, "// New%s wraps a variant for sending.\n", tn)
	fmt.Fprintf(b, "func New%s(v any) (%s, error) {\n\tdata, err := json.Marshal(v)\n\tif err != nil {\n\t\treturn %s{}, err\n\t}\n\tvar u %s\n\terr = u.UnmarshalJSON(data)\n\treturn u, err\n}\n", tn, tn, tn, tn)
}

// writeRawUnion declares a union with no discriminator, such as a value that
// is either a string or an object. It stays raw JSON; its string members are
// offered as ready-made values and its object members as their own structs.
func (g *gen) writeRawUnion(b *strings.Builder, tn string, n node) {
	fmt.Fprintf(b, "type %s json.RawMessage\n\n", tn)
	fmt.Fprintf(b, "func (u %s) MarshalJSON() ([]byte, error) {\n\tif len(u) == 0 {\n\t\treturn []byte(\"null\"), nil\n\t}\n\treturn u, nil\n}\n\n", tn)
	fmt.Fprintf(b, "func (u *%s) UnmarshalJSON(data []byte) error {\n\t*u = append((*u)[:0], data...)\n\treturn nil\n}\n\n", tn)
	fmt.Fprintf(b, "// String returns the value when it is a JSON string, and \"\" otherwise.\nfunc (u %s) String() string {\n\tvar s string\n\tif json.Unmarshal(u, &s) != nil {\n\t\treturn \"\"\n\t}\n\treturn s\n}\n\n", tn)
	var vars []string
	for _, v := range variants(n) {
		vn, ok := v.(map[string]any)
		if !ok {
			continue
		}
		if hasType(vn, "string") {
			for _, x := range list(vn, "enum") {
				s, _ := x.(string)
				d := comment(str(vn, "description"), "\t")
				vars = append(vars, fmt.Sprintf("%s\t%s%s = %s(`%q`)\n", d, tn, pascal(s), tn, s))
			}
			continue
		}
		if title := str(vn, "title"); title != "" && (hasType(vn, "object") || vn["properties"] != nil) {
			name := typeName(title)
			g.inline[name] = vn
			g.need(name)
		}
	}
	if len(vars) > 0 {
		b.WriteString("var (\n")
		for _, v := range vars {
			b.WriteString(v)
		}
		b.WriteString(")\n")
	}
}

// goType returns the Go type for a schema, declaring named types for anything
// that needs one. ctx names an anonymous nested type.
func (g *gen) goType(n node, ctx string) string {
	n, _ = nonNull(n)
	if ref := str(n, "$ref"); ref != "" {
		name := refName(ref)
		g.need(name)
		return typeName(name)
	}
	if len(variants(n)) > 0 {
		name := ctx
		if t := str(n, "title"); t != "" {
			name = typeName(t)
		}
		g.inline[name] = n
		g.need(name)
		return typeName(name)
	}
	switch {
	case hasType(n, "string"):
		return "string"
	case hasType(n, "integer"):
		return "int64"
	case hasType(n, "number"):
		return "float64"
	case hasType(n, "boolean"):
		return "bool"
	case hasType(n, "array"):
		items, _ := n["items"].(map[string]any)
		if items == nil {
			return "[]json.RawMessage"
		}
		return "[]" + g.goType(items, ctx+"Item")
	case hasType(n, "object") || n["properties"] != nil:
		if props, _ := n["properties"].(map[string]any); len(props) > 0 {
			name := ctx
			if t := str(n, "title"); t != "" {
				name = typeName(t)
			}
			g.inline[name] = n
			g.need(name)
			return typeName(name)
		}
		if ap, ok := n["additionalProperties"].(map[string]any); ok {
			return "map[string]" + g.goType(ap, ctx+"Value")
		}
		return "map[string]json.RawMessage"
	}
	return "json.RawMessage"
}

// --- methods ---

type method struct{ name, params, kind string }

func (g *gen) methods(union, kind string) []method {
	u, _ := g.top[union].(map[string]any)
	var out []method
	for _, v := range variants(u) {
		vn := v.(map[string]any)
		props, _ := vn["properties"].(map[string]any)
		m, _ := props["method"].(map[string]any)
		e := list(m, "enum")
		if len(e) != 1 {
			continue
		}
		p := ""
		if pn, ok := props["params"].(map[string]any); ok {
			if ref := str(pn, "$ref"); ref != "" {
				p = refName(ref)
			}
		}
		out = append(out, method{name: e[0].(string), params: p, kind: kind})
	}
	return out
}

func (g *gen) writeMethods(b *bytes.Buffer) {
	all := append(g.methods("ClientRequest", "client request"), g.methods("ClientNotification", "client notification")...)
	all = append(all, g.methods("ServerRequest", "server request")...)
	all = append(all, g.methods("ServerNotification", "server notification")...)
	seen := map[string]bool{}
	b.WriteString("// Method names, from the ClientRequest, ClientNotification, ServerRequest\n// and ServerNotification unions.\nconst (\n")
	for _, m := range all {
		id := "Method" + pascal(m.name)
		if seen[id] {
			continue
		}
		seen[id] = true
		params := ""
		if m.params != "" {
			params = "; params " + m.params
		}
		fmt.Fprintf(b, "\t%s = %q // %s%s\n", id, m.name, m.kind, params)
	}
	b.WriteString(")\n\n")
}
